version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "--workers=1", "app:APP", "-b", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker"]
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    volumes:
      # - ./:/usr/src/app
      - ./templates:/usr/src/app/templates
      - ./static:/usr/src/app/static
    env_file:
      - .configs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 3G